version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/moviepwa
      - TEST_MONGODB_URI=mongodb://mongodb:27017/test_db
      - JWT_SECRET=dazdazdsdsqd
      - PORT=5001
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && node seed/seed.js && npm start"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=Strongpassword1!
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data: